---
  - name: Check google-talkplugin
    shell: rpm -q google-talkplugin
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Install google-talkplugin
    dnf: name=https://dl.google.com/linux/direct/google-talkplugin_current_{{ ansible_architecture }}.rpm state=present
    when: result|failed
  - name: Fix google-talkplugin repo gpgkey
    ini_file: dest=/etc/yum.repos.d/google-talkplugin.repo section=google-talkplugin option=gpgkey value="https://dl-ssl.google.com/linux/linux_signing_key.pub"

