---
  - name: Install chromium
    dnf: name=chromium state=present
  - name: Install chromium codecs
    dnf: name=chromium-libs-media-freeworld state=present
  - name: Create temp dir for extracting plugins
    file: path=/tmp/chromium_plugins state=directory


  #- name: Download Google Chrome (with plugins)
  #  get_url: url=https://dl.google.com/linux/direct/google-chrome-stable_current_{{ ansible_architecture }}.rpm dest=/tmp/chromium_plugins/google-chrome-stable_current_{{ ansible_architecture }}.rpm
  #- name: Unpack Google Chrome rpm
  #  shell: "rpm2cpio google-chrome-stable_current_{{ ansible_architecture }}.rpm | cpio -idmv"
  #  args:
  #    chdir: /tmp/chromium_plugins/
  #    creates: /tmp/chromium_plugins/opt/google/chrome/
  #- name: Create dir for chromium plugins
  #  file: path=/usr/lib64/chromium-plugins state=directory
  #- name: Copy Widevine
  #  shell: "rsync -a /tmp/chromium_plugins/opt/google/chrome/libwidevinecdm* /usr/lib64/chromium-plugins/"

  - name: Download widevine plugin
    shell: "wget -O /tmp/chromium_plugins/widevine.zip https://dl.google.com/widevine-cdm/`wget -qO- https://dl.google.com/widevine-cdm/current.txt`-linux-`uname -m | sed 's/x86_64/x64/;s/i[56]86/ia32/'`.zip"
    args:
      creates: /tmp/chromium_plugins/widevine.zip
  - name: Unpack widevine plugin
    shell: unzip widevine.zip libwidevinecdm.so
    args:
      chdir: /tmp/chromium_plugins/
      creates: /tmp/chromium_plugins/libwidevinecdm.so
  - name: Copy widevine to /usr/local/lib64/
    copy: remote_src=True src=/tmp/chromium_plugins/libwidevinecdm.so dest=/usr/local/lib64/libwidevinecdm.so mode=0755
  - name: Add new alternative for libwidevine
    shell: alternatives --install /usr/lib64/chromium-browser/libwidevinecdm.so libwidevinecdm.so /usr/local/lib64/libwidevinecdm.so 20
  - name: Change libwidevine alternative
    shell: "echo 2 | alternatives --config libwidevinecdm.so"

  - name: Remove temp dir
    file: path=/tmp/chromium_plugins state=absent

