---
  - name: Install mplayer and vlc
    dnf: name={{ item }} state=present
    with_items:
    - mplayer
    - vlc

  - name: Make sure openh264 repo is enabled
    command: dnf config-manager --set-enabled fedora-cisco-openh264

  - name: Install codecs
    dnf: name={{ item }} state=present
    with_items:
    - gstreamer1-plugin-mpg123
    - gstreamer1-plugin-openh264
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-libav
    - gstreamer1-vaapi

  #
  # Check if var_user is valid
  #
  - name: Check if username is valid
    shell: ls -d /home/{{ var_user }}
    register: result
    changed_when: "result.rc != 0"

  #
  # Setup mplayer
  #
  - name: Create directory for config of mplayer
    file: dest="/home/{{ var_user }}/.mplayer" state=directory mode=755 owner={{ var_user }} group={{ var_user }}
  - name: Copy config of mplayer
    copy: src=mplayer.config dest=/home/{{ var_user }}/.mplayer/config mode=644 owner={{ var_user }} group={{ var_user }}
  - name: Create mplayer-speed
    copy: src=mplayer-speed dest=/usr/local/bin/mplayer-speed mode=755 owner=root group=root
  - name: Create mplayer-quality
    copy: src=mplayer-quality dest=/usr/local/bin/mplayer-quality mode=755 owner=root group=root

  #
  # Setup vlc
  #
  - name: Check vlcrc
    shell: ls /home/{{ var_user }}/.config/vlc/vlcrc
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Create vlcrc dir
    file: path=/home/{{ var_user }}/.config/vlc state=directory mode=755 owner={{ var_user }} group={{ var_user }}
    when: result|failed
  - name: Copy vlcrc file
    copy: src=vlcrc dest=/home/{{ var_user }}/.config/vlc/vlcrc mode=600 owner={{ var_user }} group={{ var_user }}
    when: result|failed

  - name: Check vlc file caching
    shell: grep 'file-caching=30000' /home/{{ var_user }}/.config/vlc/vlcrc
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Fix vlc file caching
    shell: "sed -i s/.*file-caching.*/file-caching=30000/ /home/{{ var_user }}/.config/vlc/vlcrc"
    when: result|failed

  - name: Check vlc live caching
    shell: grep 'live-caching=30000' /home/{{ var_user }}/.config/vlc/vlcrc
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Fix vlc live caching
    shell: "sed -i s/.*live-caching.*/live-caching=30000/ /home/{{ var_user }}/.config/vlc/vlcrc"
    when: result|failed

  - name: Check vlc disc caching
    shell: grep 'disc-caching=30000' /home/{{ var_user }}/.config/vlc/vlcrc
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Fix vlc disc caching
    shell: "sed -i s/.*disc-caching.*/disc-caching=30000/ /home/{{ var_user }}/.config/vlc/vlcrc"
    when: result|failed

  - name: Check vlc network caching
    shell: grep 'network-caching=30000' /home/{{ var_user }}/.config/vlc/vlcrc
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Fix vlc network caching
    shell: "sed -i s/.*network-caching.*/network-caching=30000/ /home/{{ var_user }}/.config/vlc/vlcrc"
    when: result|failed

  - name: Create vlc-speed
    copy: src=vlc-speed dest=/usr/local/bin/vlc-speed mode=755 owner=root group=root
  - name: Create vlc-quality
    copy: src=vlc-quality dest=/usr/local/bin/vlc-quality mode=755 owner=root group=root

  - name: Install pkgs for VDPAU accel for Intel
    dnf: name={{ item }} state=present
    with_items:
    - libvdpau-va-gl
    - vdpauinfo
    - libva-utils
    - libva-intel-driver
  - name: Export VDPAU settings
    copy: src=vdpau.sh dest=/etc/profile.d/vdpau.sh mode=755 owner=root group=root

