---
  #
  # Setup sane daemon
  #
  - name: Install sane-backends
    dnf: name=sane-backends state=present
  - name: Copy udev rule to set proper group
    copy: src=70-saned.rules dest=/usr/lib/udev/rules.d/70-saned.rules mode=644 owner=root group=root
    register: result
  - name: Apply new rules
    shell: udevadm control --reload
    when: result.changed
  - name: Configure sane clinet
    lineinfile: dest=/etc/sane.d/net.conf line='localhost'
  - name: Configure sane daemon - add local subnet
    lineinfile: dest=/etc/sane.d/saned.conf line='{{ var_serverip }}/24'
  - name: Create rc-local file
    file: path=/etc/rc.d/rc.local state=touch mode="u=rwx,g=rx,o=rx"
  - name: Start with /usr/bin/bash
    lineinfile: dest=/etc/rc.d/rc.local insertbefore=BOF state=present line="#!/usr/bin/bash"
  - name: Add starting sane daemon
    lineinfile: dest=/etc/rc.d/rc.local state=present line="/usr/sbin/saned -a {{ var_cifsname }}"
  - name: Start rc-local
    service: name=rc-local state=started enabled=yes


