---
#
  - name: Check skype
    shell: rpm -q skype
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Install skype
    dnf: name=http://download.skype.com/linux/skype-4.3.0.37-fedora.i586.rpm state=present
    when: result|failed


