---
  #
  # Configure power saving
  #
  - name: Start tuned
    service: name=tuned state=started enabled=yes
  - name: Check powertop-profile
    shell: tuned-adm list | grep powertop-profile
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Set profile powersave
    shell: tuned-adm profile powersave
    when: result|failed
  - name: Create powertop-profile
    shell: powertop2tuned -e -f powertop-profile
    when: result|failed
  - name: Check profile
    shell: tuned-adm active | grep powersave
    register: result
    ignore_errors: True
    changed_when: "result.rc != 0"
  - name: Set profile powersave
    shell: tuned-adm profile powersave
    when: result|failed
  - name: Copy udev rules
    copy: src=powersave.rules dest=/etc/udev/rules.d/powersave.rules mode=644 owner=root group=root
    register: result
  - name: Apply new rules
    shell: udevadm control --reload
    when: result.changed
  #
  # Disable turbo / overclocking
  #
  - name: Check if turbo is supported
    shell: /usr/bin/echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
    register: result
    ignore_errors: True
  - name: Create rc-local file
    file: path=/etc/rc.d/rc.local state=touch mode="u=rwx,g=rx,o=rx"
    when: result|succeeded
  - name: Start with /usr/bin/bash
    lineinfile: dest=/etc/rc.d/rc.local insertbefore=BOF state=present line="#!/usr/bin/bash"
    when: result|succeeded
  - name: Disable turbo
    lineinfile: dest=/etc/rc.d/rc.local state=present line="/usr/bin/echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo"
    when: result|succeeded
  - name: Start rc-local
    service: name=rc-local state=started enabled=yes
    when: result|succeeded

