---
  - name: Make sure openh264 repo is enabled
    command: dnf config-manager --set-enabled fedora-cisco-openh264

  - name: Install codecs
    dnf: name={{ item }} state=present
    with_items:
    - gstreamer1-plugin-openh264
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-base
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly-free

